name: ewartagbkp
description: e_Absensi

publish_to: "none"

version: 1.0.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  stacked: ^2.2.3
  auto_route:
  stacked_services: ^0.8.13

  cloud_firestore:
  firebase:
  firebase_core:
  firebase_storage:

  faker_dart: ^0.0.9
  intl: ^0.17.0
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.0.9

  path_provider: ^2.0.4
  flutter_pdfview: ^1.0.4
  file_picker:
  thumbnailer: ^2.0.1

  http: ^0.13.3
  external_app_launcher: ^2.0.2
  launch_review: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  stacked_generator:
  auto_route_generator:
  build_runner:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/cat.png

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.otf
        - asset: lib/assets/fonts/Poppins-Bold.otf
          weight: 700
